# -*- coding: utf-8 -*-
"""Table i18n - Storyboard IA (récit narratif autour des KPIs, §7.4). id: (fr, en, es, ar, ja, zh)."""

TRANSLATIONS = {
    'nav.storyboard': ('Storyboard IA', 'AI storyboard', 'Storyboard de IA', 'سرد الذكاء الاصطناعي', 'AIストーリーボード', 'AI 叙事板'),

    'storyboard.title': ('Storyboard IA', 'AI storyboard', 'Storyboard de IA', 'سرد الذكاء الاصطناعي', 'AIストーリーボード', 'AI 叙事板'),
    'storyboard.subtitle': ("L'IA rédige un récit narratif autour de vos indicateurs (KPIs, tendances, alertes) pour une revue de direction — elle commente uniquement les chiffres fournis.", 'AI writes a narrative around your indicators (KPIs, trends, alerts) for a management review — it comments only on the figures provided.', 'La IA redacta un relato en torno a sus indicadores (KPI, tendencias, alertas) para una revisión por la dirección — solo comenta las cifras facilitadas.', 'يكتب الذكاء الاصطناعي سردًا حول مؤشراتك (مؤشرات الأداء، الاتجاهات، التنبيهات) لمراجعة الإدارة — ويعلّق فقط على الأرقام المقدمة.', 'AIが指標（KPI・トレンド・アラート）に基づく記述をマネジメントレビュー向けに作成します — 提供された数値のみにコメントします。', 'AI 围绕您的指标（KPI、趋势、告警）撰写叙事，用于管理评审 — 仅评论所提供的数据。'),

    'storyboard.input-panel': ('Indicateurs & période', 'Indicators & period', 'Indicadores y periodo', 'المؤشرات والفترة', '指標と期間', '指标与周期'),
    'storyboard.period-label': ('Période', 'Period', 'Periodo', 'الفترة', '期間', '周期'),
    'storyboard.period-hint': ('Ex. « Mai 2026 », « T1 2026 »', 'E.g. "May 2026", "Q1 2026"', 'P. ej. «mayo 2026», «T1 2026»', 'مثل «مايو 2026»، «الربع الأول 2026»', '例：「2026年5月」「2026年第1四半期」', '例如“2026年5月”“2026年第一季度”'),
    'storyboard.context-label': ('Contexte (optionnel)', 'Context (optional)', 'Contexto (opcional)', 'السياق (اختياري)', 'コンテキスト（任意）', '背景（可选）'),
    'storyboard.context-hint': ('Ex. « Site de Lyon, atelier mécanique »', 'E.g. "Lyon site, machine shop"', 'P. ej. «sede de Lyon, taller mecánico»', 'مثل «موقع ليون، ورشة ميكانيكية»', '例：「リヨン拠点、機械工場」', '例如“里昂工厂，机加工车间”'),

    'storyboard.indicators-label': ('Indicateurs', 'Indicators', 'Indicadores', 'المؤشرات', '指標', '指标'),
    'storyboard.col-label': ('Libellé', 'Label', 'Etiqueta', 'التسمية', 'ラベル', '标签'),
    'storyboard.col-value': ('Valeur', 'Value', 'Valor', 'القيمة', '値', '数值'),
    'storyboard.col-unit': ('Unité', 'Unit', 'Unidad', 'الوحدة', '単位', '单位'),
    'storyboard.col-trend': ('Tendance', 'Trend', 'Tendencia', 'الاتجاه', 'トレンド', '趋势'),
    'storyboard.col-target': ('Cible', 'Target', 'Objetivo', 'الهدف', '目標', '目标'),
    'storyboard.ph-label': ('Taux de NC', 'NC rate', 'Tasa de NC', 'معدل عدم المطابقة', 'NC率', '不合格率'),
    'storyboard.ph-value': ('1,8', '1.8', '1,8', '1.8', '1.8', '1.8'),
    'storyboard.ph-unit': ('%', '%', '%', '٪', '%', '%'),
    'storyboard.ph-trend': ('-12 %', '-12 %', '-12 %', '-12٪', '-12%', '-12%'),
    'storyboard.ph-target': ('< 2', '< 2', '< 2', '< 2', '< 2', '< 2'),
    'storyboard.add-row': ('Ajouter un indicateur', 'Add indicator', 'Añadir indicador', 'إضافة مؤشر', '指標を追加', '添加指标'),
    'storyboard.remove-row': ('Retirer', 'Remove', 'Quitar', 'إزالة', '削除', '移除'),

    'storyboard.generate': ('Générer le récit', 'Generate narrative', 'Generar el relato', 'إنشاء السرد', '記述を生成', '生成叙事'),
    'storyboard.generating': ('Rédaction…', 'Writing…', 'Redactando…', 'جارٍ الكتابة…', '作成中…', '撰写中…'),
    'storyboard.example': ('Exemple', 'Example', 'Ejemplo', 'مثال', '例', '示例'),

    'storyboard.result-panel': ('Récit', 'Narrative', 'Relato', 'السرد', '記述', '叙事'),
    'storyboard.sources-panel': ('Chiffres source', 'Source figures', 'Cifras de origen', 'الأرقام المصدر', '元データ', '原始数据'),
    'storyboard.provider': ('Généré par', 'Generated by', 'Generado por', 'تم الإنشاء بواسطة', '生成元', '生成者'),
    'storyboard.disclaimer': ('Récit généré par IA, à valider par un humain. Aucune décision ne doit reposer sur ce texte sans vérification des chiffres source.', 'AI-generated narrative, to be validated by a human. No decision should rely on this text without checking the source figures.', 'Relato generado por IA, a validar por una persona. Ninguna decisión debe basarse en este texto sin verificar las cifras de origen.', 'سرد منشأ بالذكاء الاصطناعي، يجب التحقق منه بشريًا. لا ينبغي أن يستند أي قرار إلى هذا النص دون مراجعة الأرقام المصدر.', 'AIが生成した記述です。人間による検証が必要です。元データを確認せずにこの文章だけで判断しないでください。', '此叙事由 AI 生成，需由人工核实。在未核对原始数据前，任何决策都不应仅依据本文。'),

    'storyboard.err-period': ('Indiquez une période.', 'Provide a period.', 'Indique un periodo.', 'حدّد فترة.', '期間を指定してください。', '请提供周期。'),
    'storyboard.err-points': ('Saisissez au moins un indicateur (libellé + valeur).', 'Enter at least one indicator (label + value).', 'Introduzca al menos un indicador (etiqueta + valor).', 'أدخل مؤشرًا واحدًا على الأقل (التسمية + القيمة).', '少なくとも1つの指標（ラベル＋値）を入力してください。', '请至少输入一个指标（标签 + 数值）。'),
    'storyboard.err-backend': ('Backend injoignable (engine sur 8082 ?).', 'Backend unreachable (engine on 8082?).', 'Backend inaccesible (¿engine en 8082?).', 'تعذّر الوصول إلى الخادم (engine على 8082؟).', 'バックエンドに到達できません（engine は 8082？）。', '无法连接后端（engine 在 8082？）。'),
    'storyboard.err-invalid': ('Requête invalide (période + au moins un indicateur libellé/valeur).', 'Invalid request (period + at least one labelled/valued indicator).', 'Solicitud no válida (periodo + al menos un indicador con etiqueta/valor).', 'طلب غير صالح (الفترة + مؤشر واحد على الأقل بتسمية/قيمة).', '無効なリクエスト（期間＋ラベル/値付きの指標が1つ以上）。', '请求无效（周期 + 至少一个带标签/数值的指标）。'),
    'storyboard.err-too-large': ('Trop d\'indicateurs (garde-fou IA).', 'Too many indicators (AI guardrail).', 'Demasiados indicadores (barrera de IA).', 'عدد كبير جدًا من المؤشرات (حاجز أمان الذكاء الاصطناعي).', '指標が多すぎます（AIガードレール）。', '指标过多（AI 防护）。'),
    'storyboard.err-quota': ('Débit/quota IA dépassé pour ce tenant — réessayez plus tard.', 'AI rate/quota exceeded for this tenant — try again later.', 'Tasa/cuota de IA superada para este inquilino — inténtelo más tarde.', 'تم تجاوز معدّل/حصة الذكاء الاصطناعي لهذا المستأجر — أعد المحاولة لاحقًا.', 'このテナントのAIレート/クォータを超過しました — 後で再試行してください。', '该租户的 AI 速率/配额已超出 — 请稍后重试。'),
    'storyboard.err-gateway': ('Passerelle IA indisponible (ai-service injoignable).', 'AI gateway unavailable (ai-service unreachable).', 'Pasarela de IA no disponible (ai-service inaccesible).', 'بوابة الذكاء الاصطناعي غير متاحة (ai-service غير قابل للوصول).', 'AIゲートウェイが利用できません（ai-service に到達不可）。', 'AI 网关不可用（无法连接 ai-service）。'),
    'storyboard.err-unavailable': ('Service IA momentanément indisponible (disjoncteur ouvert).', 'AI service temporarily unavailable (circuit breaker open).', 'Servicio de IA temporalmente no disponible (disyuntor abierto).', 'خدمة الذكاء الاصطناعي غير متاحة مؤقتًا (قاطع الدائرة مفتوح).', 'AIサービスは一時的に利用できません（サーキットブレーカー作動中）。', 'AI 服务暂时不可用（断路器已打开）。'),
    'storyboard.err-generic': ('Échec de la génération (HTTP {$status}).', 'Generation failed (HTTP {$status}).', 'Fallo de la generación (HTTP {$status}).', 'فشل الإنشاء (HTTP {$status}).', '生成に失敗しました（HTTP {$status}）。', '生成失败（HTTP {$status}）。'),
}
