"""Exercise the **real** ONNX inference path against the committed toy model.

Unlike ``test_onnx_backend.py`` (which mocks ``onnxruntime.InferenceSession``),
this module loads the genuine ``models/vision5s-toy.onnx`` shipped in the repo
and runs it through a real ``onnxruntime`` session. It proves that:

- the committed ``.onnx`` is loadable and satisfies the I/O contract
  (input NCHW float32 0..1, output 1x5 pillar scores 0..1),
- the factory selects ``OnnxInferenceBackend`` (not the stub) when the model is
  present and the runtime is installed,
- the real inference output is well-formed AND deterministic per image,
- the ONNX result is computed from the model (not the SHA-based stub heuristic).

The toy model is generated by ``scripts/export_5s_model.py``. It is NOT a quality
model — it maps the mean RGB of the image to 5 pillar logits via a tiny linear
layer + sigmoid. See the runbook for replacing it with a real YOLOv8 export.

The whole module is skipped when ``onnxruntime`` / ``onnx`` are not installed
(they are optional deps — see ``pyproject.toml`` ``[onnx]`` extra), so the suite
stays green on environments without the runtime.
"""

from __future__ import annotations

import os

import pytest

# Optional runtime: skip the whole module if not installed.
pytest.importorskip("onnxruntime")
pytest.importorskip("onnx")

from app.domain.analyzer import DeterministicStubBackend  # noqa: E402
from app.infrastructure import backend_factory  # noqa: E402
from app.infrastructure.backend_factory import build_backend  # noqa: E402
from app.infrastructure.onnx_backend import OnnxInferenceBackend  # noqa: E402

_MODEL_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "models",
    "vision5s-toy.onnx",
)


def test_committed_toy_model_exists():
    assert os.path.isfile(_MODEL_PATH), (
        f"toy model missing: {_MODEL_PATH} — regenerate with "
        "`python scripts/export_5s_model.py`"
    )


def test_factory_selects_real_onnx_with_committed_model(monkeypatch):
    """With the committed model + runtime installed, the factory must pick the
    REAL ONNX backend, not the stub."""
    monkeypatch.setenv(backend_factory.ENV_MODEL_PATH, _MODEL_PATH)
    monkeypatch.setenv(backend_factory.ENV_INPUT_SIZE, "64")
    backend = build_backend()
    assert isinstance(backend, OnnxInferenceBackend)


def test_real_onnx_inference_produces_valid_score(jpeg_bytes):
    """Run the genuine onnxruntime session over the committed model."""
    backend = OnnxInferenceBackend(_MODEL_PATH, input_size=64)
    result = backend.analyze(jpeg_bytes, 320, 240)

    assert len(result.image_sha256) == 64
    assert result.width == 320 and result.height == 240
    # Output contract: 5 pillar scores scaled to 0..100, overall = mean.
    d = result.score.as_dict()
    for pillar in ("seiri", "seiton", "seiso", "seiketsu", "shitsuke", "overall"):
        assert 0 <= d[pillar] <= 100
    expected_overall = round(
        (d["seiri"] + d["seiton"] + d["seiso"] + d["seiketsu"] + d["shitsuke"]) / 5
    )
    assert d["overall"] == expected_overall
    # Findings, if any, follow the < 60 threshold rule.
    for f in result.findings:
        assert 0.0 <= f.confidence <= 1.0


def test_real_onnx_inference_is_deterministic(jpeg_bytes):
    """Same image -> identical scores across runs (no randomness)."""
    backend = OnnxInferenceBackend(_MODEL_PATH, input_size=64)
    r1 = backend.analyze(jpeg_bytes, 320, 240)
    r2 = backend.analyze(jpeg_bytes, 320, 240)
    assert r1.score.as_dict() == r2.score.as_dict()


def test_real_onnx_is_image_dependent(jpeg_bytes, png_bytes):
    """Two visually different images must yield different pillar scores,
    proving the model actually consumes the pixels (not a constant output)."""
    backend = OnnxInferenceBackend(_MODEL_PATH, input_size=64)
    s_jpeg = backend.analyze(jpeg_bytes, 320, 240).score.as_dict()
    s_png = backend.analyze(png_bytes, 320, 240).score.as_dict()
    assert s_jpeg != s_png


def test_real_onnx_differs_from_stub(jpeg_bytes):
    """The ONNX path computes scores from the model, NOT via the stub's
    SHA-256 heuristic — for the same image the two backends differ.

    (A clash is astronomically unlikely; if the toy weights ever happened to
    reproduce the stub's digest-derived scores, regenerate would change it.)"""
    onnx_score = OnnxInferenceBackend(_MODEL_PATH, input_size=64).analyze(
        jpeg_bytes, 320, 240
    ).score.as_dict()
    stub_score = DeterministicStubBackend().analyze(
        jpeg_bytes, 320, 240
    ).score.as_dict()
    assert onnx_score != stub_score
