-- Seed initial du catalogue Poka-Yoke (CLAUDE.md §3.4).
-- 12 dispositifs representatifs couvrant les principaux mecanismes Shingo.

INSERT INTO pokayoke_devices (code, name, description, type, mechanism, applicable_industries, examples, implementation_cost, created_at, updated_at)
VALUES
('PY-SHAPE-CONN-001',
 'Connecteur asymétrique anti-montage inversé',
 'Forme physique du connecteur empêchant physiquement un montage dans le mauvais sens (cle USB, connecteur D-Sub).',
 'PREVENTION', 'PHYSICAL_SHAPE',
 'manufacturing,automotive,electronics',
 'USB-A polarité, connecteurs aero asymétriques, châssis de batterie automobile',
 'low', now(), now()),

('PY-INTERLOCK-DOOR-001',
 'Verrouillage porte machine pendant operation',
 'Interlock mecanique/electrique empechant l''ouverture de la porte de la machine tant que cycle en cours.',
 'PREVENTION', 'INTERLOCK',
 'manufacturing,automotive,food,pharma',
 'Presse plieuse, autoclave pharma, four de traitement thermique',
 'medium', now(), now()),

('PY-SENSOR-WEIGHT-001',
 'Capteur de poids verification kit complet',
 'Pesee automatique apres assemblage : si poids hors tolerance, alarme et arret de ligne.',
 'DETECTION', 'SENSOR',
 'manufacturing,pharma,electronics,food',
 'Detection piece manquante dans un kit, ampoules pharma incomplètes, plateaux repas',
 'medium', now(), now()),

('PY-VISION-LABEL-001',
 'Verification visuelle etiquetage (CV/YOLO)',
 'Camera + modele de vision verifiant la presence, l''orientation et le contenu d''etiquettes produit.',
 'DETECTION', 'VISION',
 'pharma,food,manufacturing,cosmetics',
 'Conformite etiquette posologie pharma, DLC alimentaire, lot/SN moules plastique',
 'high', now(), now()),

('PY-CHECKLIST-PRE-001',
 'Checklist obligatoire pre-demarrage',
 'Validation electronique d''une checklist (signature) avant declenchement du cycle de production.',
 'PREVENTION', 'CHECKLIST',
 'all',
 'Pre-vol aero, demarrage de quart usine, ouverture salle d''operation',
 'low', now(), now()),

('PY-COLOR-WIRE-001',
 'Codage couleur cables critiques',
 'Couleur normee par fonction du cable rendant les confusions immediatement visibles.',
 'PREVENTION', 'COLOR_CODING',
 'electronics,automotive,aerospace,energy',
 'Code couleur cables electriques (rouge=+/noir=-), gaz medicaux (oxygene=blanc)',
 'low', now(), now()),

('PY-LIMIT-SW-DEPTH-001',
 'Fin de course profondeur usinage',
 'Capteur fin de course physique limitant la profondeur de penetration outil.',
 'PREVENTION', 'LIMIT_SWITCH',
 'manufacturing,automotive,aerospace',
 'Percage, fraisage, pose vis a profondeur controlee',
 'low', now(), now()),

('PY-POSITION-JIG-001',
 'Gabarit positionnel piece',
 'Gabarit physique sur poste assemblage garantissant un positionnement unique de la piece.',
 'PREVENTION', 'POSITION_REFERENCE',
 'manufacturing,automotive,electronics,aerospace',
 'Pose composant electronique sur PCB, montage sub-assembly automobile',
 'low', now(), now()),

('PY-COUNTER-CYCLE-001',
 'Compteur cycles + alerte renouvellement',
 'Compteur d''operations declenchant un signal a N cycles (maintenance, remplacement consommable).',
 'DETECTION', 'COUNTER',
 'manufacturing,medical,automotive',
 'Remplacement filtre apres N cycles, calibration outil tous les N usages',
 'low', now(), now()),

('PY-SOFTWARE-INPUT-001',
 'Validation logicielle des saisies utilisateur',
 'Controles syntaxiques + logiques + plages valides sur formulaires applicatifs.',
 'PREVENTION', 'SOFTWARE_VALIDATION',
 'all',
 'Saisie dosage medicament (plage), code IBAN (regex), poids commande (>= 0)',
 'low', now(), now()),

('PY-SENSOR-TEMP-001',
 'Detection excursion temperature chaine froid',
 'Sonde T° + seuils haut/bas avec coupure auto et alarme si depassement.',
 'DETECTION', 'SENSOR',
 'pharma,food,logistics,medical',
 'Frigos vaccins, transport produits chimiques sensibles, plats traiteur',
 'medium', now(), now()),

('PY-VISION-OPERATOR-001',
 'Detection EPI operateur (vision)',
 'Camera + modele detectant le port effectif d''EPI (casque, gants, lunettes) avant autorisation acces zone.',
 'PREVENTION', 'VISION',
 'manufacturing,construction,chemistry,mining',
 'Entree zone chantier, atelier soudure, salle blanche, manipulation produits dangereux',
 'high', now(), now());
