package com.openlab.qualitos.quality.dashboards.export.infrastructure;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import com.openlab.qualitos.quality.dashboards.export.domain.DashboardExportModel;
import com.openlab.qualitos.quality.dashboards.export.domain.DashboardPdfRenderPort;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.graphics.image.LosslessFactory;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import org.springframework.stereotype.Component;

import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.EnumMap;
import java.util.Map;

/**
 * Renders a dashboard into a premium, self-contained A4 PDF using Apache PDFBox,
 * with a verification QR code generated by ZXing (CLAUDE.md §7.4 — "PDF avec
 * signature ML-DSA + QR code blockchain").
 *
 * <p>The PDF is the QualitOS officialise-able artifact: cover title, tenant
 * metadata, a widget table (titles + supplied snapshot data), and an integrity
 * footer carrying the SHA-256 fingerprint, the verification code and a scannable
 * QR pointing at the public verify endpoint. Text drawn into the PDF is sanitised
 * to the WinAnsi range supported by the standard fonts (no exotic glyph crashes).
 */
@Component
public class PdfBoxDashboardRenderAdapter implements DashboardPdfRenderPort {

    private static final DateTimeFormatter TS =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'").withZone(ZoneOffset.UTC);

    // Palette (QualitOS premium — indigo on light).
    private static final float[] INDIGO = {0.224f, 0.286f, 0.671f};   // #3949ab
    private static final float[] INK = {0.102f, 0.102f, 0.180f};      // #1a1a2e
    private static final float[] MUTED = {0.45f, 0.45f, 0.50f};
    private static final float[] PANEL = {0.96f, 0.97f, 0.99f};

    private static final float MARGIN = 48f;
    private static final float WIDTH = PDRectangle.A4.getWidth();
    private static final float HEIGHT = PDRectangle.A4.getHeight();
    private static final float CONTENT_W = WIDTH - 2 * MARGIN;

    @Override
    public byte[] render(DashboardExportModel model, String verifyUrl) {
        try (PDDocument doc = new PDDocument()) {
            PDType1Font regular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
            PDType1Font bold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font mono = new PDType1Font(Standard14Fonts.FontName.COURIER);

            PDPage page = new PDPage(PDRectangle.A4);
            doc.addPage(page);
            float y = HEIGHT - MARGIN;

            try (PDPageContentStream c = new PDPageContentStream(doc, page)) {
                y = drawHeader(c, bold, regular, model, y);
                y = drawMetadata(c, bold, regular, model, y);
                drawWidgets(c, bold, regular, model, y);
                drawFooter(doc, c, bold, regular, mono, model, verifyUrl);
            }

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            doc.save(out);
            return out.toByteArray();
        } catch (IOException e) {
            throw new UncheckedIOException("dashboard PDF render failed", e);
        }
    }

    private float drawHeader(PDPageContentStream c, PDType1Font bold, PDType1Font regular,
                             DashboardExportModel model, float y) throws IOException {
        text(c, bold, 22, INDIGO, MARGIN, y, sanitize(model.dashboardName()));
        y -= 8;
        line(c, INDIGO, MARGIN, y, WIDTH - MARGIN, y, 2f);
        y -= 18;
        text(c, regular, 10, MUTED, MARGIN, y,
                "Export de tableau de bord - QualitOS (signe ML-DSA + ancre blockchain)");
        return y - 26;
    }

    private float drawMetadata(PDPageContentStream c, PDType1Font bold, PDType1Font regular,
                               DashboardExportModel model, float y) throws IOException {
        float boxH = 78f;
        rect(c, PANEL, MARGIN, y - boxH, CONTENT_W, boxH);
        float ix = MARGIN + 14;
        float iy = y - 18;
        kv(c, bold, regular, ix, iy, "Tableau de bord", model.dashboardId());
        kv(c, bold, regular, ix, iy - 18, "Tenant", model.tenantId());
        kv(c, bold, regular, ix, iy - 36, "Genere le", TS.format(model.generatedAt()));
        kv(c, bold, regular, ix, iy - 54, "Code de verification", model.verificationCode());
        return y - boxH - 26;
    }

    private void drawWidgets(PDPageContentStream c, PDType1Font bold, PDType1Font regular,
                             DashboardExportModel model, float y) throws IOException {
        text(c, bold, 14, INDIGO, MARGIN, y, "Widgets (" + model.widgets().size() + ")");
        y -= 18;
        if (model.widgets().isEmpty()) {
            text(c, regular, 11, MUTED, MARGIN, y, "Aucun widget sur ce tableau de bord.");
            return;
        }
        // Single-page report: keep widget content above the fixed footer zone.
        float floor = MARGIN + 210;
        int drawn = 0;
        for (DashboardExportModel.Widget w : model.widgets()) {
            if (y - 16 < floor) {
                int remaining = model.widgets().size() - drawn;
                text(c, regular, 9, MUTED, MARGIN, y, "... et " + remaining + " widget(s) supplementaire(s).");
                y -= 13;
                break;
            }
            text(c, bold, 11, INK, MARGIN, y,
                    "- " + sanitize(w.title()) + (w.type().isBlank() ? "" : "  [" + sanitize(w.type()) + "]"));
            y -= 14;
            for (String dl : w.dataLines()) {
                if (y - 13 < floor) break;
                text(c, regular, 10, MUTED, MARGIN + 16, y, sanitize(dl));
                y -= 13;
            }
            y -= 6;
            drawn++;
        }
    }

    private void drawFooter(PDDocument doc, PDPageContentStream c,
                            PDType1Font bold, PDType1Font regular, PDType1Font mono,
                            DashboardExportModel model, String verifyUrl) throws IOException {
        float footerTop = MARGIN + 150;
        line(c, MUTED, MARGIN, footerTop, WIDTH - MARGIN, footerTop, 0.5f);
        float y = footerTop - 18;
        text(c, bold, 12, INDIGO, MARGIN, y, "Integrite & verification");
        y -= 16;
        text(c, regular, 9, INK, MARGIN, y,
                "Ce document est signe (Ed25519 + ML-DSA-65) et ancre sur blockchain.");
        y -= 13;
        text(c, regular, 9, INK, MARGIN, y,
                "Son empreinte SHA-256 est scellee cote serveur sous le code ci-dessous.");
        // Verification instructions (the QR carries the public verify URL).
        text(c, regular, 8, MUTED, MARGIN, MARGIN + 30,
                "Scannez le QR code pour verifier l'authenticite de ce document sur QualitOS.");
        text(c, mono, 8, INK, MARGIN, MARGIN + 16,
                "Code : " + model.verificationCode());

        // QR on the right, pointing at the public verify endpoint.
        float qrSize = 110f;
        PDImageXObject qr = qrImage(doc, verifyUrl, qrSize);
        c.drawImage(qr, WIDTH - MARGIN - qrSize, MARGIN + 12, qrSize, qrSize);
    }

    // ---- low-level drawing ----

    private void kv(PDPageContentStream c, PDType1Font bold, PDType1Font regular,
                    float x, float y, String key, String value) throws IOException {
        text(c, bold, 9, MUTED, x, y, key);
        text(c, regular, 10, INK, x + 130, y, sanitize(value));
    }

    private void text(PDPageContentStream c, PDType1Font font, float size,
                      float[] color, float x, float y, String s) throws IOException {
        c.beginText();
        c.setFont(font, size);
        c.setNonStrokingColor(color[0], color[1], color[2]);
        c.newLineAtOffset(x, y);
        c.showText(s == null ? "" : s);
        c.endText();
    }

    private void line(PDPageContentStream c, float[] color, float x1, float y1,
                      float x2, float y2, float w) throws IOException {
        c.setStrokingColor(color[0], color[1], color[2]);
        c.setLineWidth(w);
        c.moveTo(x1, y1);
        c.lineTo(x2, y2);
        c.stroke();
    }

    private void rect(PDPageContentStream c, float[] color, float x, float y,
                      float w, float h) throws IOException {
        c.setNonStrokingColor(color[0], color[1], color[2]);
        c.addRect(x, y, w, h);
        c.fill();
    }

    private PDImageXObject qrImage(PDDocument doc, String content, float px) {
        try {
            Map<EncodeHintType, Object> hints = new EnumMap<>(EncodeHintType.class);
            hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.M);
            hints.put(EncodeHintType.MARGIN, 1);
            int size = Math.round(px) * 2;
            BitMatrix matrix = new QRCodeWriter().encode(
                    content, BarcodeFormat.QR_CODE, size, size, hints);
            BufferedImage img = new BufferedImage(size, size, BufferedImage.TYPE_INT_RGB);
            int black = 0x000000;
            int white = 0xFFFFFF;
            for (int x = 0; x < size; x++) {
                for (int yy = 0; yy < size; yy++) {
                    img.setRGB(x, yy, matrix.get(x, yy) ? black : white);
                }
            }
            return LosslessFactory.createFromImage(doc, img);
        } catch (Exception e) {
            throw new IllegalStateException("QR generation failed", e);
        }
    }

    /** Restrict to WinAnsi-safe characters (standard fonts cannot encode arbitrary Unicode). */
    private static String sanitize(String s) {
        if (s == null) return "";
        StringBuilder b = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char ch = s.charAt(i);
            if (ch >= 32 && ch < 127) {
                b.append(ch);
            } else {
                switch (ch) {
                    case 'é', 'è', 'ê', 'ë' -> b.append('e');
                    case 'à', 'â', 'ä' -> b.append('a');
                    case 'î', 'ï' -> b.append('i');
                    case 'ô', 'ö' -> b.append('o');
                    case 'û', 'ü', 'ù' -> b.append('u');
                    case 'ç' -> b.append('c');
                    case 'É', 'È', 'Ê' -> b.append('E');
                    case 'À', 'Â' -> b.append('A');
                    case '’', '‘' -> b.append('\'');
                    case '–', '—' -> b.append('-');
                    default -> b.append('?');
                }
            }
        }
        return b.toString();
    }
}
